const fiftyDollars = [
    "Captain America",
    "Spider-Man (Avengers: Infinity War)",
    "Groot (Avengers: Infinity War)",
    "Black Panther",
    "Iron Man Mk XLVI (Captain America: Civil War)",
    "The Classic Master Box Set",
    "Ant-Man",
    "Captain America (Avengers: Endgame)",
    "Captain Marvel",
    "Loki (The Avengers)",
    "Star-Lord (Avengers: Infinity War)",
    "Thor (Avengers: Infinity War)",
    "War Machine (Iron Man 2)",
    "Winter Soldier (Avengers: Infinity War)"
]
const fourtyFiveDollars = [
    "Bane Special Edition",
    "1st Doctor & Susan, Ian and Barbara Companion Set (Black and White Variant)",
    "Weeping Angel (Statue of Liberty)",
    "Cyber-Controller on Throne",
    "Rhaegal Dragon",
    "Viserion Dragon"
];
const fourtyDollars = [
    "4 Doctors Set",
    "WWE Wrestlemania 25 Double Pack: The Undertaker & Shawn Michaels",
    "WWE Iconic Tag Team: Rock ’N’ Sock Connection",
    "The Eighth Doctor, Liv Chenka, Dalek (Big Finish) Figurine Set",
    "Star Trek Tardigrade Figure (Ripper)",
    "The Incredible Hulk & She-Hulk (Hero Rooks) Special Edition",
    "Baby Nifflers",
    "WWE Iconic Tag Team: Edge & Christian",
    "Iron Man Mark VII Helmet Replica",
    "Black Panther’s Mask Replica",
    "The Infinity Gauntlet Replica",
    "Captain America’s Shield Replica",
    "Mjolnir (Thor's Hammer) Replica",
    "Revolution of the Daleks Set",
    "WWE Iconic Family: Jim \"The Anvil\" Neidhart & Natalya",
    "Green Goblin Marvel VS.",
    "Iron Man Marvel VS.",
    "Captain America Marvel VS.",
    "Spider-Man Marvel VS.",
    "Thor Marvel VS.",
    "Loki Marvel VS."
]
const thirtyFiveDollars = [
    "4 Doctors Set",
    "Kroton Special Edition",
    "4th Doctor & Sarah Jane Companion Set",
    "Dragon Biomechanoid",
    "Ace & The Seventh Doctor Companion Set",
    "Dalek Drone and Dalek Emperor Set",
    "Superman and Wonder Woman Boxset",
    "Dalek Time Commander and Dalek Scientist Set",
    "Missy and Rassilon Time Lords Set",
    "The Melkur"
];
const thirtyDollars = [
    "Rubeus Hagrid Special Edition",
    "8th Doctor, Lucie Miller, Dale Companion Set",
    "Dobby the Elf"
]
const twentyFiveDollars = [
    "Evolution of The Cybermen Set 2",
    "2nd Doctor & Jamie McCrimmon",
    "The Niffler (Fantastic Beasts)",
    "Pickett the Bowtruckle",
    "Borusa and Romana Time Lords Set",
    "Rob Gronkowski",
    "Pennywise (IT: Chapter Two)",
    "Pennywise (IT, 1990)",
    "Annabelle (Annabelle Comes Home)",
    "Valak (The Nun)",
    "The Crooked Man",
    "Stripe (Gremlins)",
    "Batmobile (Batman 1966)",
    "Batmobile (Batman 1989)"
]
const twentyDollars = [
    "Cyber Controller",
    "Silurian Warrior",
    "Time Lord Rassilon",
    "Omega",
    "Kahler-Tek",
    "Terileptil Leader",
    "Dalek Sec Hybrid",
    "Auton",
    "Chantho",
    "Venom (Black Pawn)",
    "Scarecrow",
    "Jabe",
    "Sensorite",
    "Sontaran Commander Linx",
    "The Hath",
    "Carrionite",
    "The Destroyer",
    "Penguin",
    "Poison Ivy",
    "The Joker",
    "Robin",
    "Ice Queen",
    "Superman",
    "Two-Face",
    "Golden Eagle Armor Wonder Woman",
    "Wonder Woman",
    "Green Lantern",
    "First Appearance Wonder Woman",
    "Stone Dalek",
    "Classic Ice Warrior",
    "Martian Manhunter",
    "Professor Dumbledore (Michael Gambon)",
    "Divine Armor Wonder Woman",
    "Lord Voldemort (Battle of Hogwarts)",
    "Dementor (Guard of Azkaban)",
    "Newt Scamander",
    "Occamy",
    "Tina Goldstein",
    "Queenie Goldstein",
    "Harry Potter (Battle of Hogwarts)",
    "Fawkes",
    "Ron Weasley with Scabbers",
    "AJ Styles",
    "Hermione Granger",
    "Albus Dumbledore (Fantastic Beasts)",
    "Batman",
    "Xavier Woods",
    "The Undertaker",
    "Braun Strowman",
    "Batman and The Joker Boxset",
    "Joker",
    "The Rock",
    "Seth Rollins",
    "Bellatrix Lestrange",
    "Harley Quinn",
    "Gellert Grindelwald (Fantastic Beasts)",
    "Theseus Scamander (Fantastic Beasts)",
    "Sniper Bot",
    "Macho Man Randy Savage",
    "Triple H",
    "Alastor Mad-Eye Moody",
    "Luna Lovegood",
    "Bayley",
    "Bret Hart",
    "Ray Stantz",
    "Egon Spengler",
    "Scarecrow",
    "Seraphina Picquery (Fantastic Beasts)",
    "Leta Lestrange (Fantastic Beasts)",
    "Daniel Bryan",
    "Peter Venkman",
    "Minerva McGonagall",
    "Ronda Rousey",
    "Kofi Kingston",
    "Winston Zeddemore",
    "Batman Silver Age 1960s",
    "Batman Bronze Age 1970s",
    "Batman Modern Age 1980s",
    "Batman Debut 1940s",
    "Kurt Angle",
    "Batman Golden Age 1950s",
    "Jacob Kowalski (Fantastic Beasts)",
    "Dougal Demiguise (Fantastic Beasts)",
    "Lucius Malfoy",
    "Draco Malfoy (Death Eater)",
    "Cyber Scout",
    "Ribbons of the Seven Stomachs",
    "New Paradigm Eternal Dalek",
    "The Morax Queen",
    "Lin-Dalek",
    "Batman Modern Age 1990s",
    "Batman Modern Age 2000s",
    "Kevin Owens",
    "Slimer (The Green Ghost)",
    "Big E",
    "Sami Zayn",
    "Asuka",
    "Becky Lynch",
    "Credence Barebone Figurine (Fantastic Beasts)",
    "Maledictus Figurine (Fantastic Beasts)",
    "Neville Longbottom",
    "Nagini",
    "Ginny Weasley",
    "Samoa Joe",
    "T’zim-Sha",
    "Dolores Umbridge",
    "Pete Dunne",
    "Shinsuke Nakamura",
    "Nicolas Flamel (Fantastic Beasts)",
    "Yusuf Kama (Fantastic Beasts)",
    "Steve Austin",
    "Cactus Jack",
    "The Miz",
    "Ron Weasley 7th Year (Harry Potter)",
    "Hermione Granger 7th Year (Harry Potter)",
    "Batman Modern Age 2010s",
    "Super Voc",
    "Pol-Kon-Don (Judoon Captain)",
    "The Monk and The Master Time Lords Figurine Set",
    "Albus Dumbledore (Richard Harris)",
    "Percival Graves",
    "Fred Weasley",
    "George Weasley",
    "Cho Chang",
    "Razor Ramon",
    "Victor Zsasz",
    "Peter Pettigrew",
    "Cedric Diggory",
    "Hermione Granger (Yule Ball)",
    "Remus Lupin",
    "The Dreg",
    "Harry Potter (Yule Ball)",
    "Novice Hame",
    "Sea Devil Warrior",
    "Garrick Ollivander",
    "Hulk Hogan",
    "Eddie Guerrero",
    "Jeff Hardy",
    "Ric Flair",
    "The Skithran Queen",
    "The Fugitive Doctor",
    "The Snowman",
    "Spider-Man (Hero Knight)",
    "Iron Man (Hero Bishop)",
    "The Toymaker",
    "Wolverine (Hero Knight)",
    "Loki (Villain Bishop)",
    "Professor Pomona Sprout",
    "Professor Filius Flitwick",
    "Newt Scamander Figurine (Fantastic Beasts 2)",
    "Ron Weasley Figurine (Yule Ball)",
    "Professor Quirinus Quirrell",
    "Gilderoy Lockhart",
    "Morty Smith",
    "Mr. Meeseeks",
    "Summer Smith",
    "Griphook",
    "Amazing Spider-Man #65 Felipe Massafera Eaglemoss Exclusive Variant",
    "Mestor",
    "Chameleon",
    "Bok",
    "Primord",
    "Navarino",
    "Mutt",
    "Batman (White King)",
    "Joker (Black King)",
    "Robin (White Bishop)",
    "The Penguin (Black Knight)",
    "Catwoman (White Queen)",
    "Batgirl (White Knight)",
    "Two Face (Black Knight)"
];

const makeUpchargeArray = (count, amount) => new Array(count).fill(amount);

const upcharge = [
    ...makeUpchargeArray(twentyDollars.length, 0),
    ...makeUpchargeArray(twentyFiveDollars.length, 5),
    ...makeUpchargeArray(thirtyDollars.length, 10),
    ...makeUpchargeArray(thirtyFiveDollars.length, 15),
    ...makeUpchargeArray(fourtyDollars.length, 20),
    ...makeUpchargeArray(fourtyFiveDollars.length, 25),
    ...makeUpchargeArray(fiftyDollars.length, 30)
];
export default [{
    name: 'Character',
    options: [
        ...twentyDollars,
        ...twentyFiveDollars,
        ...thirtyDollars,
        ...thirtyFiveDollars,
        ...fourtyDollars,
        ...fourtyFiveDollars,
        ...fiftyDollars
    ],
    upcharge
}];